// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wsgi.proto

package wsgi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Config struct {
	Ip                   string      `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 uint32      `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	IsIPv6               bool        `protobuf:"varint,3,opt,name=isIPv6,proto3" json:"isIPv6,omitempty"`
	IdChecksum           *IdChecksum `protobuf:"bytes,4,opt,name=idChecksum,proto3" json:"idChecksum,omitempty"`
	NumWorkers           uint32      `protobuf:"varint,5,opt,name=numWorkers,proto3" json:"numWorkers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1efff2af16158bd, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Config) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Config) GetIsIPv6() bool {
	if m != nil {
		return m.IsIPv6
	}
	return false
}

func (m *Config) GetIdChecksum() *IdChecksum {
	if m != nil {
		return m.IdChecksum
	}
	return nil
}

func (m *Config) GetNumWorkers() uint32 {
	if m != nil {
		return m.NumWorkers
	}
	return 0
}

type IdChecksum struct {
	IdChecksum           uint64   `protobuf:"fixed64,1,opt,name=idChecksum,proto3" json:"idChecksum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdChecksum) Reset()         { *m = IdChecksum{} }
func (m *IdChecksum) String() string { return proto.CompactTextString(m) }
func (*IdChecksum) ProtoMessage()    {}
func (*IdChecksum) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1efff2af16158bd, []int{1}
}

func (m *IdChecksum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdChecksum.Unmarshal(m, b)
}
func (m *IdChecksum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdChecksum.Marshal(b, m, deterministic)
}
func (m *IdChecksum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdChecksum.Merge(m, src)
}
func (m *IdChecksum) XXX_Size() int {
	return xxx_messageInfo_IdChecksum.Size(m)
}
func (m *IdChecksum) XXX_DiscardUnknown() {
	xxx_messageInfo_IdChecksum.DiscardUnknown(m)
}

var xxx_messageInfo_IdChecksum proto.InternalMessageInfo

func (m *IdChecksum) GetIdChecksum() uint64 {
	if m != nil {
		return m.IdChecksum
	}
	return 0
}

type Wsgi struct {
	Version              *Wsgi_Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	UrlScheme            string        `protobuf:"bytes,2,opt,name=url_scheme,json=urlScheme,proto3" json:"url_scheme,omitempty"`
	InputStream          string        `protobuf:"bytes,3,opt,name=input_stream,json=inputStream,proto3" json:"input_stream,omitempty"`
	ErrorStream          string        `protobuf:"bytes,4,opt,name=error_stream,json=errorStream,proto3" json:"error_stream,omitempty"`
	Multithreaded        bool          `protobuf:"varint,5,opt,name=multithreaded,proto3" json:"multithreaded,omitempty"`
	Multiprocess         bool          `protobuf:"varint,6,opt,name=multiprocess,proto3" json:"multiprocess,omitempty"`
	RunOnce              bool          `protobuf:"varint,7,opt,name=run_once,json=runOnce,proto3" json:"run_once,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Wsgi) Reset()         { *m = Wsgi{} }
func (m *Wsgi) String() string { return proto.CompactTextString(m) }
func (*Wsgi) ProtoMessage()    {}
func (*Wsgi) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1efff2af16158bd, []int{2}
}

func (m *Wsgi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wsgi.Unmarshal(m, b)
}
func (m *Wsgi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wsgi.Marshal(b, m, deterministic)
}
func (m *Wsgi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wsgi.Merge(m, src)
}
func (m *Wsgi) XXX_Size() int {
	return xxx_messageInfo_Wsgi.Size(m)
}
func (m *Wsgi) XXX_DiscardUnknown() {
	xxx_messageInfo_Wsgi.DiscardUnknown(m)
}

var xxx_messageInfo_Wsgi proto.InternalMessageInfo

func (m *Wsgi) GetVersion() *Wsgi_Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Wsgi) GetUrlScheme() string {
	if m != nil {
		return m.UrlScheme
	}
	return ""
}

func (m *Wsgi) GetInputStream() string {
	if m != nil {
		return m.InputStream
	}
	return ""
}

func (m *Wsgi) GetErrorStream() string {
	if m != nil {
		return m.ErrorStream
	}
	return ""
}

func (m *Wsgi) GetMultithreaded() bool {
	if m != nil {
		return m.Multithreaded
	}
	return false
}

func (m *Wsgi) GetMultiprocess() bool {
	if m != nil {
		return m.Multiprocess
	}
	return false
}

func (m *Wsgi) GetRunOnce() bool {
	if m != nil {
		return m.RunOnce
	}
	return false
}

type Wsgi_Version struct {
	Major                uint32   `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor                uint32   `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wsgi_Version) Reset()         { *m = Wsgi_Version{} }
func (m *Wsgi_Version) String() string { return proto.CompactTextString(m) }
func (*Wsgi_Version) ProtoMessage()    {}
func (*Wsgi_Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1efff2af16158bd, []int{2, 0}
}

func (m *Wsgi_Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wsgi_Version.Unmarshal(m, b)
}
func (m *Wsgi_Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wsgi_Version.Marshal(b, m, deterministic)
}
func (m *Wsgi_Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wsgi_Version.Merge(m, src)
}
func (m *Wsgi_Version) XXX_Size() int {
	return xxx_messageInfo_Wsgi_Version.Size(m)
}
func (m *Wsgi_Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Wsgi_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Wsgi_Version proto.InternalMessageInfo

func (m *Wsgi_Version) GetMajor() uint32 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *Wsgi_Version) GetMinor() uint32 {
	if m != nil {
		return m.Minor
	}
	return 0
}

type Environ struct {
	RequestMethod        string            `protobuf:"bytes,1,opt,name=request_method,json=requestMethod,proto3" json:"request_method,omitempty"`
	ScriptName           string            `protobuf:"bytes,2,opt,name=script_name,json=scriptName,proto3" json:"script_name,omitempty"`
	PathInfo             string            `protobuf:"bytes,3,opt,name=path_info,json=pathInfo,proto3" json:"path_info,omitempty"`
	QueryString          string            `protobuf:"bytes,4,opt,name=query_string,json=queryString,proto3" json:"query_string,omitempty"`
	ContentType          string            `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ContentLength        string            `protobuf:"bytes,6,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	ServerName           string            `protobuf:"bytes,7,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerPort           string            `protobuf:"bytes,8,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
	ServerProtocol       string            `protobuf:"bytes,9,opt,name=server_protocol,json=serverProtocol,proto3" json:"server_protocol,omitempty"`
	HttpRequestHeaders   map[string]string `protobuf:"bytes,10,rep,name=http_request_headers,json=httpRequestHeaders,proto3" json:"http_request_headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Wsgi                 *Wsgi             `protobuf:"bytes,11,opt,name=wsgi,proto3" json:"wsgi,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Environ) Reset()         { *m = Environ{} }
func (m *Environ) String() string { return proto.CompactTextString(m) }
func (*Environ) ProtoMessage()    {}
func (*Environ) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1efff2af16158bd, []int{3}
}

func (m *Environ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Environ.Unmarshal(m, b)
}
func (m *Environ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Environ.Marshal(b, m, deterministic)
}
func (m *Environ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Environ.Merge(m, src)
}
func (m *Environ) XXX_Size() int {
	return xxx_messageInfo_Environ.Size(m)
}
func (m *Environ) XXX_DiscardUnknown() {
	xxx_messageInfo_Environ.DiscardUnknown(m)
}

var xxx_messageInfo_Environ proto.InternalMessageInfo

func (m *Environ) GetRequestMethod() string {
	if m != nil {
		return m.RequestMethod
	}
	return ""
}

func (m *Environ) GetScriptName() string {
	if m != nil {
		return m.ScriptName
	}
	return ""
}

func (m *Environ) GetPathInfo() string {
	if m != nil {
		return m.PathInfo
	}
	return ""
}

func (m *Environ) GetQueryString() string {
	if m != nil {
		return m.QueryString
	}
	return ""
}

func (m *Environ) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Environ) GetContentLength() string {
	if m != nil {
		return m.ContentLength
	}
	return ""
}

func (m *Environ) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *Environ) GetServerPort() string {
	if m != nil {
		return m.ServerPort
	}
	return ""
}

func (m *Environ) GetServerProtocol() string {
	if m != nil {
		return m.ServerProtocol
	}
	return ""
}

func (m *Environ) GetHttpRequestHeaders() map[string]string {
	if m != nil {
		return m.HttpRequestHeaders
	}
	return nil
}

func (m *Environ) GetWsgi() *Wsgi {
	if m != nil {
		return m.Wsgi
	}
	return nil
}

type Header struct {
	Status               string            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ResponseHeaders      map[string]string `protobuf:"bytes,2,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1efff2af16158bd, []int{4}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Header) GetResponseHeaders() map[string]string {
	if m != nil {
		return m.ResponseHeaders
	}
	return nil
}

type Response struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1efff2af16158bd, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Config)(nil), "wsgi.Config")
	proto.RegisterType((*IdChecksum)(nil), "wsgi.IdChecksum")
	proto.RegisterType((*Wsgi)(nil), "wsgi.Wsgi")
	proto.RegisterType((*Wsgi_Version)(nil), "wsgi.Wsgi.Version")
	proto.RegisterType((*Environ)(nil), "wsgi.Environ")
	proto.RegisterMapType((map[string]string)(nil), "wsgi.Environ.HttpRequestHeadersEntry")
	proto.RegisterType((*Header)(nil), "wsgi.Header")
	proto.RegisterMapType((map[string]string)(nil), "wsgi.Header.ResponseHeadersEntry")
	proto.RegisterType((*Response)(nil), "wsgi.Response")
}

func init() { proto.RegisterFile("wsgi.proto", fileDescriptor_c1efff2af16158bd) }

var fileDescriptor_c1efff2af16158bd = []byte{
	// 669 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xd1, 0x4e, 0xdb, 0x3a,
	0x18, 0xc7, 0x95, 0x52, 0xd2, 0xe6, 0x4b, 0x0b, 0xc8, 0x42, 0xe7, 0xe4, 0x70, 0x74, 0x38, 0xa5,
	0x02, 0xad, 0x17, 0xa8, 0x9a, 0x98, 0x36, 0x4d, 0xbb, 0x1c, 0x43, 0xa2, 0x12, 0xdb, 0x90, 0x99,
	0xc6, 0x65, 0x14, 0x52, 0xd3, 0x78, 0x34, 0x76, 0xb0, 0x9d, 0x4e, 0x7d, 0x81, 0x3d, 0xc2, 0x1e,
	0x64, 0xd2, 0xde, 0x6f, 0xf2, 0x67, 0x07, 0x5a, 0x6d, 0xbb, 0xd8, 0x9d, 0xfd, 0xf3, 0xdf, 0xce,
	0xff, 0xfb, 0xfb, 0x73, 0x00, 0x3e, 0xeb, 0x19, 0x1f, 0x57, 0x4a, 0x1a, 0x49, 0xda, 0x76, 0x3c,
	0xfc, 0x1a, 0x40, 0x78, 0x2a, 0xc5, 0x2d, 0x9f, 0x91, 0x2d, 0x68, 0xf1, 0x2a, 0x09, 0x06, 0xc1,
	0x28, 0xa2, 0x2d, 0x5e, 0x11, 0x02, 0xed, 0x4a, 0x2a, 0x93, 0xb4, 0x06, 0xc1, 0xa8, 0x4f, 0x71,
	0x4c, 0xfe, 0x82, 0x90, 0xeb, 0xc9, 0xe5, 0xe2, 0x45, 0xb2, 0x31, 0x08, 0x46, 0x5d, 0xea, 0x67,
	0xe4, 0x29, 0x00, 0x9f, 0x9e, 0x16, 0x2c, 0xbf, 0xd3, 0x75, 0x99, 0xb4, 0x07, 0xc1, 0x28, 0x3e,
	0xd9, 0x19, 0xe3, 0xd7, 0x26, 0x0f, 0x9c, 0xae, 0x68, 0xc8, 0x3e, 0x80, 0xa8, 0xcb, 0x6b, 0xa9,
	0xee, 0x98, 0xd2, 0xc9, 0x26, 0x7e, 0x63, 0x85, 0x0c, 0x8f, 0x01, 0x26, 0x6b, 0xea, 0x95, 0xf3,
	0xad, 0xc7, 0x70, 0xf5, 0xb4, 0xe1, 0xf7, 0x16, 0xb4, 0xaf, 0xf5, 0x8c, 0x93, 0x63, 0xe8, 0x2c,
	0x98, 0xd2, 0x5c, 0x0a, 0x54, 0xc5, 0x27, 0xc4, 0xb9, 0xb0, 0x8b, 0xe3, 0x8f, 0x6e, 0x85, 0x36,
	0x12, 0xf2, 0x1f, 0x40, 0xad, 0xe6, 0xa9, 0xce, 0x0b, 0x56, 0x32, 0x2c, 0x34, 0xa2, 0x51, 0xad,
	0xe6, 0x57, 0x08, 0xc8, 0x01, 0xf4, 0xb8, 0xa8, 0x6a, 0x93, 0x6a, 0xa3, 0x58, 0x56, 0x62, 0xcd,
	0x11, 0x8d, 0x91, 0x5d, 0x21, 0xb2, 0x12, 0xa6, 0x94, 0x54, 0x8d, 0xa4, 0xed, 0x24, 0xc8, 0xbc,
	0xe4, 0x10, 0xfa, 0x65, 0x3d, 0x37, 0xdc, 0x14, 0x8a, 0x65, 0x53, 0x36, 0xc5, 0x62, 0xbb, 0x74,
	0x1d, 0x92, 0x21, 0xf4, 0x10, 0x54, 0x4a, 0xe6, 0x4c, 0xeb, 0x24, 0x44, 0xd1, 0x1a, 0x23, 0xff,
	0x40, 0x57, 0xd5, 0x22, 0x95, 0x22, 0x67, 0x49, 0x07, 0xd7, 0x3b, 0xaa, 0x16, 0xef, 0x45, 0xce,
	0xf6, 0x9e, 0x43, 0xc7, 0x57, 0x47, 0x76, 0x61, 0xb3, 0xcc, 0x3e, 0x49, 0x85, 0x01, 0xf4, 0xa9,
	0x9b, 0x20, 0xe5, 0x42, 0x2a, 0x7f, 0x9d, 0x6e, 0x32, 0xfc, 0xd2, 0x86, 0xce, 0x99, 0x58, 0x70,
	0x25, 0x05, 0x39, 0x82, 0x2d, 0xc5, 0xee, 0x6b, 0xa6, 0x4d, 0x5a, 0x32, 0x53, 0xc8, 0xa9, 0xef,
	0x85, 0xbe, 0xa7, 0x6f, 0x11, 0x92, 0xff, 0x21, 0xd6, 0xb9, 0xe2, 0x95, 0x49, 0x45, 0xf6, 0x10,
	0x1a, 0x38, 0xf4, 0x2e, 0x2b, 0x19, 0xf9, 0x17, 0xa2, 0x2a, 0x33, 0x45, 0xca, 0xc5, 0xad, 0xf4,
	0x91, 0x75, 0x2d, 0x98, 0x88, 0x5b, 0x69, 0xf3, 0xba, 0xaf, 0x99, 0x5a, 0xda, 0xbc, 0xb8, 0x98,
	0x35, 0x79, 0x21, 0xbb, 0x42, 0x64, 0x25, 0xb9, 0x14, 0x86, 0x09, 0x93, 0x9a, 0x65, 0xc5, 0x30,
	0xae, 0x88, 0xc6, 0x9e, 0x7d, 0x58, 0x56, 0xcc, 0x5a, 0x6d, 0x24, 0x73, 0x26, 0x66, 0xa6, 0xc0,
	0xb8, 0x22, 0xda, 0xf7, 0xf4, 0x02, 0x21, 0x5a, 0x65, 0x6a, 0xc1, 0x94, 0xb3, 0xda, 0xf1, 0x56,
	0x11, 0xa1, 0xd5, 0x47, 0x01, 0x76, 0x7a, 0x77, 0x55, 0x70, 0x69, 0xfb, 0xfd, 0x09, 0x6c, 0x37,
	0x02, 0xfb, 0x68, 0x72, 0x39, 0x4f, 0x22, 0x14, 0x6d, 0x79, 0x91, 0xa7, 0xe4, 0x1a, 0x76, 0x0b,
	0x63, 0xaa, 0xb4, 0x49, 0xb0, 0xb0, 0xb7, 0xaa, 0x74, 0x02, 0x83, 0x8d, 0x51, 0x7c, 0x72, 0xe4,
	0x9a, 0xd0, 0x27, 0x3d, 0x3e, 0x37, 0xa6, 0xa2, 0x4e, 0x78, 0xee, 0x74, 0x67, 0xc2, 0xa8, 0x25,
	0x25, 0xc5, 0x4f, 0x0b, 0x64, 0x1f, 0xf0, 0xa1, 0x26, 0x31, 0x76, 0x33, 0x3c, 0x76, 0x33, 0x45,
	0xbe, 0x77, 0x06, 0x7f, 0xff, 0xe6, 0x38, 0xb2, 0x03, 0x1b, 0x77, 0x6c, 0xe9, 0x6f, 0xd1, 0x0e,
	0x6d, 0x13, 0x2c, 0xb2, 0x79, 0xdd, 0xdc, 0x9a, 0x9b, 0xbc, 0x6a, 0xbd, 0x0c, 0x86, 0xdf, 0x02,
	0x08, 0xdd, 0x66, 0xfb, 0xc6, 0xb5, 0xc9, 0x4c, 0xad, 0xfd, 0x4e, 0x3f, 0x23, 0x17, 0xb0, 0xa3,
	0x98, 0xae, 0xa4, 0xd0, 0xec, 0xa1, 0xbc, 0x16, 0x96, 0x77, 0xe0, 0x5c, 0xb9, 0xfd, 0x63, 0xea,
	0x45, 0x6b, 0xa5, 0x6d, 0xab, 0x75, 0xba, 0xf7, 0x1a, 0x76, 0x7f, 0x25, 0xfc, 0x23, 0xd3, 0x6f,
	0xa0, 0xdb, 0x9c, 0x41, 0x0e, 0x21, 0x74, 0xa6, 0xfc, 0xbb, 0xef, 0xad, 0x7a, 0xa2, 0x7e, 0xcd,
	0xfe, 0xd3, 0x6e, 0xe4, 0x74, 0x89, 0x47, 0xf5, 0x28, 0x8e, 0x6f, 0x42, 0xbc, 0xda, 0x67, 0x3f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x21, 0x47, 0x67, 0xd5, 0x1d, 0x05, 0x00, 0x00,
}
